# Dancing with Qubit

## Multi-qubit gates

In [ ]:
import numpy as np
import pylatexenc
import math

### Hadamard gate and n-qubits Hadamard gate

In [27]:
H_gate = np.array([[1, 1], [1, -1]]) / math.sqrt(2)

In [28]:
def Hadamard_gate(n):
    """
    Returns the n-qubit Hadamard gate as a numpy array.
    
    Parameters:
    n (int): The number of qubits.
    
    Returns:
    np.ndarray: The n-qubit Hadamard gate.
    """
    if n < 1:
        raise ValueError("n must be a positive integer.")
    
    # Start with the single qubit Hadamard gate
    gate = H_gate
    
    # Apply the Hadamard gate to each qubit
    for _ in range(1, n):
        gate = np.kron(gate, H_gate)
    
    return gate

Apply 3-qubits Hadamard gate

In [54]:
(Hadamard_gate(2))

array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5, -0.5,  0.5, -0.5],
       [ 0.5,  0.5, -0.5, -0.5],
       [ 0.5, -0.5, -0.5,  0.5]])

## Swap gate

In [30]:
Swap_gate = np.array([[1, 0, 0, 0],
                     [0, 0, 1, 0],
                     [0, 1, 0, 0],
                     [0, 0, 0, 1]])

## CX gate

In [31]:
CX_gate = np.array([[1, 0, 0, 0],
                   [0, 1, 0, 0],
                   [0, 0, 0, 1],
                   [0, 0, 1, 0]])

## Reserve_CNOT_gate

In [61]:
Reserve_CNOT_with_H = Hadamard_gate(2) @ CX_gate @ Hadamard_gate(2)
Reserve_CNOT_with_H[np.abs(Reserve_CNOT_with_H) < 1e-10] = 0

In [62]:
print(Reserve_CNOT_with_H)

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [63]:
Reserve_CNOT_with_S = Swap_gate @ CX_gate @ Swap_gate
Reserve_CNOT_with_S[np.abs(Reserve_CNOT_with_S) < 1e-10] = 0

In [64]:
print(Reserve_CNOT_with_S)

[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


## Controlling other 1-qubit gates

In [71]:
Y_gate = np.array([[0, -1j],
                  [1j, 0]])
Z_gate = np.array([[1, 0],
                  [0, -1]])
X_gate = np.array([[0, 1],
                  [1, 0]])
I_gate = np.array([[1, 0],
                   [0, 1]])
zero_gate = np.array([[0,0],
                     [0,0]])

In [72]:
CY_gate = np.array([I_gate,zero_gate,zero_gate,Y_gate,])

## The quantum ZZ and $R_{\psi}^{zz}$ gates

In [79]:
ZZ = Z_gate @ Z_gate

In [80]:
print(ZZ)

[[1 0]
 [0 1]]


In [91]:
def Rzz_gate(theta):
    """
    Returns the Rzz gate for a given angle theta.
    
    Parameters:
    theta (float): The angle in radians.
    
    Returns:
    np.ndarray: The Rzz gate as a numpy array.
    """
    num = np.cos(theta / 2) * I_gate - 1j * np.sin(theta / 2) * ZZ
    num[np.abs(num) < 1e-10] = 0
    return num


In [92]:
Rzz_gate(0)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [94]:
Rzz_gate(math.pi)

array([[6.123234e-17-1.j, 0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17-1.j]])

In [95]:
Rzz_gate(2*math.pi)

array([[-1.-1.2246468e-16j,  0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j, -1.-1.2246468e-16j]])

## The quantum Toffoli CCNOT gate

In [97]:
CCNOT = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1],
                  [0, 0, 0, 0, 0, 0, 1, 0]])


## The quantum Fredkin CSWAP gate

In [98]:
CSWAP = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1]])