# Dancing with Qubit

## 8.3 Multi-qubit gates

### Content
- The quantum $H^n$ gate
- The quantum SWAP gate
- The quantum CX gate
- Controlling other 1-qubit gate
- Quantum ZZ gate and $R_{phi}^ZZ$ gate
- The quantum Toffoli CCNOT gate
- The quantum Fredkin CSWAP gate

In [25]:
import numpy as np
import pylatexenc
import math
import scipy

### Hadamard gate and n-qubits Hadamard gate

In [3]:
H_gate = np.array([[1, 1], [1, -1]]) / math.sqrt(2)

operating on $C^2$ Starting with the two qubit states

| ${\psi \rangle}_1 = a_1 |0 \rangle_1 + b_1 | 1 \rangle_1 $ and | ${\psi \rangle}_2 = a_2 |0 \rangle_2 + b_2 | 2 \rangle_2 $

applying H to each qubit means to compute

$(H | \psi \rangle_1) \times (H | \psi \rangle_1)$

In [4]:
def Hadamard_gate(n):
    """
    Returns the n-qubit Hadamard gate as a numpy array.
    
    Parameters:
    n (int): The number of qubits.
    
    Returns:
    np.ndarray: The n-qubit Hadamard gate.
    """
    if n < 1:
        raise ValueError("n must be a positive integer.")
    
    # Start with the single qubit Hadamard gate
    gate = H_gate
    
    # Apply the Hadamard gate to each qubit
    for _ in range(1, n):
        gate = np.kron(gate, H_gate)
    
    return gate

Apply 3-qubits Hadamard gate

In [5]:
(Hadamard_gate(2))

array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5, -0.5,  0.5, -0.5],
       [ 0.5,  0.5, -0.5, -0.5],
       [ 0.5, -0.5, -0.5,  0.5]])

## Swap gate

In [6]:
Swap_gate = np.array([[1, 0, 0, 0],
                     [0, 0, 1, 0],
                     [0, 1, 0, 0],
                     [0, 0, 0, 1]])

## CX gate

In [7]:
CX_gate = np.array([[1, 0, 0, 0],
                   [0, 1, 0, 0],
                   [0, 0, 0, 1],
                   [0, 0, 1, 0]])

## Reserve_CNOT_gate

In [8]:
Reserve_CNOT_with_H = Hadamard_gate(2) @ CX_gate @ Hadamard_gate(2)
Reserve_CNOT_with_H[np.abs(Reserve_CNOT_with_H) < 1e-10] = 0

In [9]:
print(Reserve_CNOT_with_H)

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [10]:
Reserve_CNOT_with_S = Swap_gate @ CX_gate @ Swap_gate
Reserve_CNOT_with_S[np.abs(Reserve_CNOT_with_S) < 1e-10] = 0

In [11]:
print(Reserve_CNOT_with_S)

[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


## Controlling other 1-qubit gates

In [12]:
Y_gate = np.array([[0, -1j],
                  [1j, 0]])
Z_gate = np.array([[1, 0],
                  [0, -1]])
X_gate = np.array([[0, 1],
                  [1, 0]])
I_gate = np.array([[1, 0],
                   [0, 1]])
zero_gate = np.array([[0,0],
                     [0,0]])

In [13]:
CY_gate = np.array([I_gate,zero_gate,zero_gate,Y_gate,])

## The quantum ZZ and $R_{\psi}^{zz}$ gates

In [14]:
ZZ = np.kron(Z_gate,Z_gate)

In [15]:
print(ZZ)

[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]


In [28]:
def Rzz_gate(theta):
    """
    Returns the Rzz gate for a given angle theta.
    
    Parameters:
    theta (float): The angle in radians.
    
    Returns:
    np.ndarray: The Rzz gate as a numpy array.
    """
    return scipy.linalg.expm(-1j * theta / 2 * ZZ)


In [29]:
Rzz_gate(0)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [37]:
np.round(Rzz_gate(math.pi),2)

array([[0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j]])

In [38]:
np.round(Rzz_gate(2*math.pi),2)

array([[-1.-0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.-0.j]])

## The quantum Toffoli CCNOT gate

In [ ]:
CCNOT = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1],
                  [0, 0, 0, 0, 0, 0, 1, 0]])


## The quantum Fredkin CSWAP gate

In [ ]:
CSWAP = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1]])